[tool.black]
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
line-length = 150
target-version = ['py37']

[tool.pytest.ini_options]
python_files = '*_tests.py'
testpaths = [
  "tests",
]

[tool.isort]
multi_line_output = 3
profile = "black"

[flake8]
exclude ='''
    .git
    __pycache__
    '''